### ISSUE TITLE
webdav总是连接失败，发现端口号总是被自动修改成5005

### ISSUE THREAD

**Issue by imysl0** [mrjoechen/ShowcaseApp#1]
如题，手机荣耀30pro，系统鸿蒙4，apk从github下载。有视频

https://github.com/mrjoechen/ShowcaseApp/assets/17337930/8e36ebba-0661-402d-bbc2-6664852d56df

**Comment by mrjoechen** [comment]
Thank you for your feedback. The latest version has fixed this issue. Please download and update the installation.
