### ISSUE TITLE
Always buffering and can't display after displaying certain pics while using SMB and there're many pics in the folder. 

### ISSUE THREAD

**Issue by RCAPSN** [mrjoechen/ShowcaseApp#4]
你好！
我使用SMB协议，并在SMB文件夹中放入了几十个图片后（每个文件都不大于500Kb，文件名为 Pic(1) Pic(2)依次类推）。
开始播放后，前面的十几个正常，十几个（有时是二十几个）过后，就不显示了，APP显示在缓冲加载，但总是不成功。

**Comment by mrjoechen** [comment]
I noticed this problem and I will try to locate it and fix it. Thanks your feedback !

**Comment by mrjoechen** [comment]
This issue has been resolved, please update to the latest version
