### ISSUE TITLE
Can't slide the videos

### ISSUE THREAD

**Issue by Stanyer** [mrjoechen/ShowcaseApp#6]
Recent releases have updated the video carousel feature, but I added a folder with videos that showed no content. What is the reason? Is it related to the video format?

**Comment by mrjoechen** [comment]
Sorry, It's a bug, It will be fixed in the next version soon. Thanks for your feedback.

**Comment by mrjoechen** [comment]
The problem you reported has been solved in the latest release version. Thanks for your feedback. ✋
